server:
  port: 9090

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: loulysoft
  #auth-server-url: http://localhost:8180/auth
  auth-server-url: http://0.0.0.0:8080 #keycloak server
  resource: springboot-keycloak #clientID
  public-client: true
  bearer-only: true